;;; Reader:由 eval 搭配字串很難測,所以直接測讀進來的字面值
(assert-equal 42 42)
(assert-equal -17 -17)
(assert-equal 3.5 3.5)
(assert-equal 100.0 1e2)
(assert-equal 0.5 .5)
(assert-equal 1/2 2/4)
(assert-equal 3 6/2)
(assert-true (exact? 1/3))
(assert-true (inexact? 1.0))
(assert-equal "a\nb" "a\nb")
(assert-equal 3 (string-length "a\tb"))
(assert-equal 2 (string-length "\"\\"))
(assert-equal "A" (string #\A))
(assert-equal 97 (char->integer #\a))
(assert-equal 32 (char->integer #\space))
(assert-equal 10 (char->integer #\newline))
(assert-equal #t #true)
(assert-equal #f #false)
(assert-equal '(1 . 2) (cons 1 2))
(assert-equal '(1 2 . 3) (cons 1 (cons 2 3)))
(assert-equal '(quote x) ''x)
(assert-equal '(quasiquote (a (unquote b) (unquote-splicing c))) '`(a ,b ,@c))
(assert-equal 3 (length '(1 ; 行註解
                          2 #| 區塊 #| 巢狀 |# 註解 |# 3)))
(assert-equal '(1 3) '(1 #;(hidden datum) 3))
(assert-equal #(1 2 3) (vector 1 2 3))
(assert-equal 255 #xFF)
(assert-equal 5 #b101)
(assert-equal 'abc (string->symbol "abc"))
(assert-equal "hello" (symbol->string 'hello))
(assert-true (eq? 'a 'a))
(assert-equal '() '())
(assert-equal '(1 2) '[1 2])
