(define x 10)
(assert-equal 10 x)
(define (add a b) (+ a b))
(assert-equal 7 (add 3 4))
(define (opt a . rest) (list a rest))
(assert-equal '(1 ()) (opt 1))
(assert-equal '(1 (2 3)) (opt 1 2 3))
(define all (lambda args args))
(assert-equal '(1 2 3) (all 1 2 3))
(assert-equal '() (all))
(assert-equal 3 ((lambda (a b) (+ a b)) 1 2))
(define (outer n)
  (define (helper k) (* k 2))
  (define base 100)
  (+ base (helper n)))
(assert-equal 110 (outer 5))
(assert-equal 'yes (if #t 'yes 'no))
(assert-equal 'no (if #f 'yes 'no))
(assert-equal 'yes (if 0 'yes 'no))
(assert-equal 'yes (if '() 'yes 'no))
(assert-equal 'neg (cond ((< -1 0) 'neg) ((> -1 0) 'pos) (else 'zero)))
(assert-equal 'zero (cond ((< 0 0) 'neg) ((> 0 0) 'pos) (else 'zero)))
(assert-equal 2 (cond ((assv 'b '((a 1) (b 2))) => cadr) (else 'none)))
(assert-equal 'none (cond ((assv 'z '((a 1))) => cadr) (else 'none)))
(assert-equal 5 (cond (5)))
(assert-equal 'small (case 3 ((1 2 3) 'small) ((4 5 6) 'big) (else 'huge)))
(assert-equal 'huge (case 99 ((1 2 3) 'small) ((4 5 6) 'big) (else 'huge)))
(assert-equal 'vowel (case #\a ((#\a #\e #\i #\o #\u) 'vowel) (else 'consonant)))
(assert-equal 'sym (case 'x ((x y) 'sym) (else 'other)))
(assert-equal #t (and))
(assert-equal 3 (and 1 2 3))
(assert-equal #f (and 1 #f 3))
(assert-equal #f (or))
(assert-equal 1 (or 1 2))
(assert-equal 2 (or #f 2))
(assert-equal 'x (when #t 'a 'x))
(assert-equal 'x (unless #f 'a 'x))
(assert-equal 3 (let ((a 1) (b 2)) (+ a b)))
(assert-equal 3 (let* ((a 1) (b (+ a 1))) (+ a b)))
(assert-equal #t (letrec ((ev? (lambda (n) (if (= n 0) #t (od? (- n 1)))))
                          (od? (lambda (n) (if (= n 0) #f (ev? (- n 1))))))
                   (ev? 100)))
(assert-equal 120 (let loop ((n 5) (acc 1)) (if (= n 0) acc (loop (- n 1) (* acc n)))))
(assert-equal 10 (do ((i 0 (+ i 1)) (s 0 (+ s i))) ((= i 5) s)))
(assert-equal '(4 3 2 1 0) (do ((i 0 (+ i 1)) (acc '() (cons i acc))) ((= i 5) acc)))
(define counter 0)
(set! counter (+ counter 1))
(assert-equal 1 counter)
(define (make-counter)
  (let ((n 0)) (lambda () (set! n (+ n 1)) n)))
(define c1 (make-counter))
(define c2 (make-counter))
(c1) (c1)
(assert-equal 3 (c1))
(assert-equal 1 (c2))
(assert-equal 3 (begin 1 2 3))
(assert-equal '(1 2) (quote (1 2)))
(define (curried a) (lambda (b) (+ a b)))
(assert-equal 5 ((curried 2) 3))
(define ((add3 a) b) (+ a b))
(assert-equal 9 ((add3 4) 5))
(define-record-type point (make-point x y) point? (x point-x set-point-x!) (y point-y))
(define p (make-point 3 4))
(assert-equal 3 (point-x p))
(assert-equal 4 (point-y p))
(set-point-x! p 30)
(assert-equal 30 (point-x p))
(assert-true (point? p))
(assert-equal #f (point? 5))
(assert-error "point-x" (point-x 5))
(define-record-type <account> (make-account owner) account? (owner account-owner) (balance account-balance set-account-balance!))
(assert-equal #f (account-balance (make-account "amy")))
(define pr (delay (begin (set! counter (+ counter 100)) counter)))
(assert-equal 101 (force pr))
(assert-equal 101 (force pr))
(assert-equal 5 (force 5))
(define s (cons-stream 1 (cons-stream 2 '())))
(assert-equal 2 (stream-car (stream-cdr s)))
(assert-equal '(1 2) (stream->list s))
