(define a 1)
(define lst '(2 3))
(assert-equal '(1 2 3) `(1 2 3))
(assert-equal '(1 2) `(,a 2))
(assert-equal '(0 1 2 3 4) `(0 ,a ,@lst 4))
(assert-equal '(2 3) `(,@lst))
(assert-equal '(1 2 3 . 4) `(1 ,@lst . 4))
(assert-equal '(1 (2 3)) `(,a (,@lst)))
(assert-equal '(x (y 1)) `(x (y ,a)))
(assert-equal #(1 2 3) `#(,a 2 3))
(assert-equal '(1 `(2 ,(3 ,a))) `(1 `(2 ,(3 ,',a))) )
(assert-equal '(quasiquote (x (unquote y))) '`(x ,y))
(assert-equal '(a (unquote-splicing b)) '(a ,@b))
(assert-equal '(1 . 2) `(,a . 2))
(assert-equal '(3) `(,(+ 1 2)))
(assert-equal '() `())
(assert-equal '(sum 6) `(sum ,(apply + '(1 2 3))))
