;;; 逃逸
(assert-equal 42 (call/cc (lambda (k) (+ 1 (k 42)))))
(assert-equal 5 (call-with-current-continuation (lambda (k) 5)))
(assert-equal 3 (+ 1 (call/cc (lambda (k) (k 2)))))
(define (find-first pred lst)
  (call/cc (lambda (return)
    (for-each (lambda (x) (if (pred x) (return x))) lst)
    #f)))
(assert-equal 4 (find-first even? '(1 3 4 5 6)))
(assert-equal #f (find-first even? '(1 3 5)))
(define (product lst)
  (call/cc (lambda (break)
    (fold-left (lambda (acc x) (if (= x 0) (break 0) (* acc x))) 1 lst))))
(assert-equal 0 (product '(1 2 0 4)))
(assert-equal 24 (product '(1 2 3 4)))

;;; 重新進入 (完整 continuation)
(define saved #f)
(define count 0)
(define result (+ 100 (call/cc (lambda (k) (set! saved k) 1))))
(set! count (+ count 1))
(if (< count 3) (saved count))
(assert-equal 3 count)
(assert-equal 102 result)

;;; generator
(define (make-gen lst)
  (define return #f)
  (define resume #f)
  (define (start)
    (for-each (lambda (x) (call/cc (lambda (next) (set! resume next) (return x)))) lst)
    (return 'done))
  (lambda ()
    (call/cc (lambda (r)
      (set! return r)
      (if resume (resume #f) (start))))))
(define g (make-gen '(a b c)))
(assert-equal 'a (g))
(assert-equal 'b (g))
(assert-equal 'c (g))
(assert-equal 'done (g))

;;; dynamic-wind
(define trace '())
(define (note x) (set! trace (cons x trace)))
(dynamic-wind (lambda () (note 'in)) (lambda () (note 'body)) (lambda () (note 'out)))
(assert-equal '(in body out) (reverse trace))
(set! trace '())
(call/cc (lambda (k)
  (dynamic-wind (lambda () (note 'in)) (lambda () (k 1) (note 'never)) (lambda () (note 'out)))))
(assert-equal '(in out) (reverse trace))
(assert-equal 7 (dynamic-wind (lambda () #f) (lambda () 7) (lambda () #f)))
(set! trace '())
(define re #f)
(define n 0)
(dynamic-wind
  (lambda () (note 'in))
  (lambda () (call/cc (lambda (k) (set! re k))) (note 'body))
  (lambda () (note 'out)))
(set! n (+ n 1))
(if (< n 2) (re #f))
(assert-equal '(in body out in body out) (reverse trace))
(set! trace '())
(catch-error
  (lambda () (dynamic-wind (lambda () (note 'in)) (lambda () (error "boom")) (lambda () (note 'out))))
  (lambda (m) (note 'handled)))
(assert-equal '(in out handled) (reverse trace))

;;; catch-error
(assert-equal "boom 1 2" (catch-error (lambda () (error "boom" 1 2)) (lambda (m) m)))
(assert-equal 'fine (catch-error (lambda () 'fine) (lambda (m) 'bad)))
(assert-equal 42 (catch-error (lambda () (raise 42)) (lambda (o) o)))
(assert-equal 'inner (catch-error (lambda () (catch-error (lambda () (error "x")) (lambda (m) 'inner))) (lambda (m) 'outer)))
(assert-equal 'outer (catch-error (lambda () (catch-error (lambda () (error "x")) (lambda (m) (error "y")))) (lambda (m) 'outer)))
(assert-true (procedure? (call/cc (lambda (k) k))))
(assert-equal 10 (apply + 1 2 '(3 4)))
(assert-equal 6 (apply + '(1 2 3)))
(assert-equal 'v (eval ''v))
(assert-equal 6 (eval '(* 2 3)))
