(assert-equal '(1 2) (cons 1 '(2)))
(assert-equal 1 (car '(1 2 3)))
(assert-equal '(2 3) (cdr '(1 2 3)))
(assert-equal 2 (cadr '(1 2 3)))
(assert-equal '(3) (cddr '(1 2 3)))
(assert-equal 3 (caddr '(1 2 3)))
(assert-equal 1 (caar '((1) 2)))
(assert-equal '(1 2 3) (list 1 2 3))
(assert-equal 3 (length '(a b c)))
(assert-equal 0 (length '()))
(assert-equal '(1 2 3 4) (append '(1 2) '(3 4)))
(assert-equal '(1 2 3) (append '(1) '(2) '(3)))
(assert-equal '(1 . 2) (append '(1) 2))
(assert-equal '() (append))
(assert-equal '(3 2 1) (reverse '(1 2 3)))
(assert-equal 'c (list-ref '(a b c d) 2))
(assert-equal '(c d) (list-tail '(a b c d) 2))
(assert-equal '(a b) (list-head '(a b c d) 2))
(assert-equal '(b c) (memq 'b '(a b c)))
(assert-equal #f (memq 'z '(a b c)))
(assert-equal '((1 2) 3) (member '(1 2) '(0 (1 2) 3)) )
(assert-equal '(b 2) (assq 'b '((a 1) (b 2))))
(assert-equal #f (assq 'z '((a 1))))
(assert-equal '("k" . 1) (assoc "k" '(("j" . 0) ("k" . 1))))
(assert-equal '(1 4 9) (map (lambda (x) (* x x)) '(1 2 3)))
(assert-equal '(5 7 9) (map + '(1 2 3) '(4 5 6)))
(assert-equal '(1 2) (map (lambda (a b) a) '(1 2 3) '(a b)))
(assert-equal '(2 4) (filter even? '(1 2 3 4 5)))
(assert-equal '(1 3 5) (remove even? '(1 2 3 4 5)))
(assert-equal 10 (fold-left + 0 '(1 2 3 4)))
(assert-equal '(((() . 1) . 2) . 3) (fold-left cons '() '(1 2 3)))
(assert-equal '(1 2 3 ()) (fold-right cons '(()) '(1 2 3)))
(assert-equal 10 (reduce + 0 '(1 2 3 4)))
(assert-equal 0 (reduce + 0 '()))
(assert-equal '(3 2 1) (fold cons '() '(1 2 3)))
(define acc '())
(for-each (lambda (x) (set! acc (cons x acc))) '(1 2 3))
(assert-equal '(3 2 1) acc)
(for-each (lambda (a b) (set! acc (cons (+ a b) acc))) '(1 2) '(10 20))
(assert-equal '(22 11 3 2 1) acc)
(assert-equal '(1 2 3 4) (sort '(3 1 4 2) <))
(assert-equal '(4 3 2 1) (sort '(3 1 4 2) >))
(assert-equal #(1 2 3) (sort #(3 2 1) <))
(assert-equal '("a" "b" "c") (sort '("c" "a" "b") string<?))
(assert-equal '(0 1 2 3) (iota 4))
(assert-equal '(1 3 5) (iota 3 1 2))
(assert-equal '(0 1 4) (list-tabulate 3 (lambda (i) (* i i))))
(assert-equal 2 (list-index even? '(1 3 2)))
(assert-equal 3 (find (lambda (x) (> x 2)) '(1 2 3 4)))
(assert-true (any even? '(1 2 3)))
(assert-equal #f (any even? '(1 3)))
(assert-true (every odd? '(1 3)))
(assert-equal '(1 2 3) (delete-duplicates '(1 2 1 3 2)))
(assert-equal '(2 3) (delete 1 '(1 2 1 3)))
(assert-equal 3 (last '(1 2 3)))
(assert-equal 2 (count even? '(1 2 4 5)))
(assert-equal '(1 2 3 4) (append-map (lambda (x) (list x (+ x 1))) '(1 3)) )
(assert-true (list? '(1 2)))
(assert-equal #f (list? '(1 . 2)))
(assert-true (pair? '(1)))
(assert-equal #f (pair? '()))
(assert-true (null? '()))
(assert-equal '(1 . 5) (let ((p (cons 1 2))) (set-cdr! p 5) p))
(assert-equal '(9 2) (let ((p (list 1 2))) (set-car! p 9) p))
(assert-true (equal? '(1 (2 #(3))) '(1 (2 #(3)))))
(assert-equal #f (equal? '(1 2) '(1 3)))
(assert-equal #f (eq? '(1) '(1)))
(assert-true (eq? '() '()))
(assert-equal 5 (vector-length (make-vector 5 0)))
(assert-equal 'x (vector-ref #(a x c) 1))
(assert-equal #(1 9 3) (let ((v (vector 1 2 3))) (vector-set! v 1 9) v))
(assert-equal '(1 2 3) (vector->list #(1 2 3)))
(assert-equal #(1 2) (list->vector '(1 2)))
(assert-equal #(2 4) (vector-map (lambda (x) (* 2 x)) #(1 2)))
(assert-equal #(7 7) (let ((v (make-vector 2 0))) (vector-fill! v 7) v))
(assert-equal #(1 2 3 4) (vector-append #(1 2) #(3 4)))
(define ht (make-equal-hash-table))
(hash-table-set! ht "a" 1)
(hash-table-set! ht '(1 2) 2)
(assert-equal 1 (hash-table-ref/default ht "a" 0))
(assert-equal 2 (hash-table-ref ht '(1 2)))
(assert-equal 0 (hash-table-ref/default ht "zz" 0))
(assert-equal 2 (hash-table-count ht))
(hash-table-update!/default ht "a" (lambda (v) (+ v 10)) 0)
(assert-equal 11 (hash-table-ref ht "a" (lambda () 'none)))
(hash-table-delete! ht "a")
(assert-equal #f (hash-table-contains? ht "a"))
(assert-equal 'none (hash-table-ref ht "a" (lambda () 'none)))
