(assert-equal 5 (string-length "hello"))
(assert-equal "hello world" (string-append "hello" " " "world"))
(assert-equal "" (string-append))
(assert-equal "ell" (substring "hello" 1 4))
(assert-equal "llo" (substring "hello" 2))
(assert-equal #\e (string-ref "hello" 1))
(assert-equal '(#\a #\b) (string->list "ab"))
(assert-equal "ab" (list->string (list #\a #\b)))
(assert-equal 'abc (string->symbol "abc"))
(assert-equal "abc" (symbol->string 'abc))
(assert-equal "HELLO" (string-upcase "hello"))
(assert-equal "hello" (string-downcase "HELLO"))
(assert-true (string=? "a" "a"))
(assert-equal #f (string=? "a" "b"))
(assert-true (string<? "apple" "banana"))
(assert-true (string-ci=? "AbC" "aBc"))
(assert-equal "olleh" (string-reverse "hello"))
(assert-equal 2 (string-index "hello" #\l))
(assert-equal 6 (string-contains "hello world" "world"))
(assert-equal #f (string-contains "hello" "xyz"))
(assert-true (string-prefix? "he" "hello"))
(assert-true (string-suffix? "lo" "hello"))
(assert-equal "a,b,c" (string-join '("a" "b" "c") ","))
(assert-equal '("a" "b" "c") (string-split "a,b,c" #\,))
(assert-equal "  42" (string-pad-left "42" 4))
(assert-equal "42  " (string-pad-right "42" 4))
(assert-equal "abc" (string-trim "  abc  "))
(assert-equal "ababab" (apply string-append (map (lambda (x) "ab") '(1 2 3))))
(assert-equal "xxx" (make-string 3 #\x))
(assert-true (string? "s"))
(assert-equal #f (string? 's))
(assert-equal #\A (char-upcase #\a))
(assert-true (char-alphabetic? #\a))
(assert-true (char-numeric? #\5))
(assert-true (char-whitespace? #\space))
(assert-equal #t (char<? #\a #\b))
(assert-equal "abc" (list->string (map char-downcase (string->list "ABC"))))
(assert-equal #\a (integer->char 97))
(assert-equal 5 (char->digit #\5 10))
(assert-equal "42" (number->string 42))
(assert-equal "(1 2 3)" (call-with-current-continuation (lambda (k) "(1 2 3)")))
(assert-equal 3 (string-length (symbol->string 'abc)))
(assert-equal "hi 3" (string-append "hi " (number->string 3)))
(assert-equal '(#\a) (string->list "a"))
(assert-equal "bcd" (string-copy "abcde" 1 4))
