;;; 錯誤訊息都是「英文 / 中文」雙語,這裡兩種語言的片段都檢查。
(assert-error "unbound variable: nope" nope)
(assert-error "未定義的變數: nope" nope)
(assert-error "unbound variable" (undefined-fn 1 2))
(assert-error "expected pair" (car 5))
(assert-error "需要序對" (cdr "str"))
(assert-error "car: expected pair, got ()" (car '()))
(assert-error "expected number" (+ 1 "a"))
(assert-error "需要數字" (* 'x 2))
(assert-error "expected number, got \"s\"" (< 1 "s"))
(assert-error "division by zero" (/ 1 0))
(assert-error "除以零" (quotient 5 0))
(assert-error "modulo: division by zero" (modulo 5 0))
(assert-error "expected string" (string-length 5))
(assert-error "expected string" (string-append "a" 1))
(assert-error "expected proper list" (length '(1 . 2)))
(assert-error "expected proper list" (length 5))
(assert-error "index" (vector-ref (vector 1 2) 5))
(assert-error "超出範圍" (vector-ref (vector 1 2) -1))
(assert-error "index out of range" (list-ref '(1 2) 9))
(assert-error "out of bounds" (substring "abc" 2 9))
(assert-error "not a procedure: 5" (5 1 2))
(assert-error "不是程序" ("str"))
(define (two a b) (+ a b))
(assert-error "procedure 'two' expects 2 argument(s), got 1" (two 1))
(assert-error "需要 2 個參數,卻收到 3 個" (two 1 2 3))
(assert-error "anonymous procedure expects 1" ((lambda (x) x)))
(define (at-least-one a . r) a)
(assert-error "at least 1" (at-least-one))
(assert-error "car expects 1 argument(s), got 2" (car 1 2))
(assert-error "cons expects 2" (cons 1))
(assert-error "vector-ref expects 2 argument(s), got 0" (+ 1 (apply vector-ref '())))
(assert-error "boom: 42" (error "boom:" 42))
(assert-error "bad thing \"str\" foo" (error "bad thing" "str" 'foo))
(assert-error "assertion failed" (assert (= 1 2)))
(assert-error "bad syntax" (eval '(if)))
(assert-error "語法錯誤" (eval '(let ((x)) )))
(assert-error "bad syntax" (eval '(lambda)))
(assert-error "must not be empty" (eval '()))
(assert-error "set!: unbound variable: zzz" (set! zzz 1))
(assert-error "unbound variable" (letrec ((a b) (b 1)) a))
(assert-error "expected proper list" (map car 5))
(assert-error "exact->inexact: expected number" (exact->inexact 'a))
(assert-error "negative argument" (sqrt -4))
(assert-error "expected character" (char-upcase "a"))
(assert-error "expected symbol" (symbol->string "a"))
(assert-error "hash table" (hash-table-set! 5 1 2))
(assert-error "key not found" (hash-table-ref (make-equal-hash-table) 'k))
(define-record-type point (make-point x y) point? (x point-x) (y point-y))
(assert-error "point-y: expected a point record" (point-y 5))
(assert-error "需要 point 記錄" (point-x (list 1 2)))
;;; 錯誤發生後,直譯器仍然可以繼續用
(assert-equal 3 (+ 1 2))
;;; Reader 錯誤 (透過 eval 不會經過 Reader,所以另外在 Python 測試)
