(define (integers-from n) (cons-stream n (integers-from (+ n 1))))
(define nat (integers-from 0))
(assert-equal '(0 1 2 3 4) (stream-head nat 5))
(assert-equal 100 (stream-ref nat 100))
(assert-equal '(0 2 4) (stream-head (stream-filter even? nat) 3))
(assert-equal '(0 1 4 9) (stream-head (stream-map square nat) 4))
(assert-equal '(1 3) (stream->list (stream-map + (list->stream '(0 1)) (list->stream '(1 2)))))
(assert-true (stream-pair? nat))
(assert-true (stream-null? the-empty-stream))
(assert-equal 2 (stream-car (stream-tail nat 2)))
(define (sieve s)
  (cons-stream (stream-car s)
    (sieve (stream-filter (lambda (x) (not (= 0 (remainder x (stream-car s))))) (stream-cdr s)))))
(assert-equal '(2 3 5 7 11 13) (stream-head (sieve (integers-from 2)) 6))
;;; delay 只會計算一次
(define calls 0)
(define d (delay (begin (set! calls (+ calls 1)) 'v)))
(force d) (force d)
(assert-equal 1 calls)
(assert-true (promise? d))
;;; 遮蔽:區域變數可以蓋掉特殊形式的名字
(assert-equal 3 (let ((if (lambda (a b c) (+ a b c)))) (if 1 1 1)))
(assert-equal '(1) (let ((list (lambda args args))) (list 1)))
;;; define 巨集名稱之後可以被覆蓋成一般函式
(define-syntax foo (syntax-rules () ((_ x) 'macro)))
(assert-equal 'macro (foo 1))
(define (foo x) 'function)
(assert-equal 'function (foo 1))
;;; 字串內含 unicode
(assert-equal 3 (string-length "你好嗎"))
(assert-equal "你好" (substring "你好嗎" 0 2))
(assert-equal 'ok (begin (define zz 1) 'ok))
(assert-equal 1 zz)
(define (f) (define a 1) (define (g) (+ a 1)) (g))
(assert-equal 2 (f))
(assert-equal '(1 2 3) (let () (define-record-type box (mk v) box? (v unbox)) (list (unbox (mk 1)) 2 3)))
(assert-equal 8 (let loop ((i 0)) (if (< i 8) (loop (+ i 1)) i)))
(assert-equal 120 ((lambda (n) (let f ((n n)) (if (= n 0) 1 (* n (f (- n 1)))))) 5))
(assert-true (procedure? car))
(assert-true (procedure? (lambda () 1)))
(assert-equal #f (procedure? 'car))
