;;; 小型 metacircular evaluator:用 Scheme 寫一個 Scheme 直譯器 (SICP 第 4 章精簡版)
;;; 支援:數字/字串/符號、quote、if、define、set!、lambda、begin、cond、let,
;;; 以及呼叫底層 Scheme 的基本程序。

(define (m-eval exp env)
  (cond ((or (number? exp) (string? exp) (boolean? exp)) exp)
        ((symbol? exp) (lookup exp env))
        ((eq? (car exp) 'quote) (cadr exp))
        ((eq? (car exp) 'if)
         (if (m-eval (cadr exp) env)
             (m-eval (caddr exp) env)
             (if (null? (cdddr exp)) #f (m-eval (cadddr exp) env))))
        ((eq? (car exp) 'define)
         (if (pair? (cadr exp))
             (define-var! (car (cadr exp))
               (make-proc (cdr (cadr exp)) (cddr exp) env) env)
             (define-var! (cadr exp) (m-eval (caddr exp) env) env)))
        ((eq? (car exp) 'set!) (set-var! (cadr exp) (m-eval (caddr exp) env) env))
        ((eq? (car exp) 'lambda) (make-proc (cadr exp) (cddr exp) env))
        ((eq? (car exp) 'begin) (eval-seq (cdr exp) env))
        ((eq? (car exp) 'cond) (eval-cond (cdr exp) env))
        ((eq? (car exp) 'let)
         (m-eval (cons (cons 'lambda (cons (map car (cadr exp)) (cddr exp)))
                       (map cadr (cadr exp)))
                 env))
        (else (m-apply (m-eval (car exp) env)
                       (map (lambda (e) (m-eval e env)) (cdr exp))))))

(define (eval-seq exps env)
  (if (null? (cdr exps))
      (m-eval (car exps) env)
      (begin (m-eval (car exps) env) (eval-seq (cdr exps) env))))

(define (eval-cond clauses env)
  (cond ((null? clauses) #f)
        ((or (eq? (caar clauses) 'else) (m-eval (caar clauses) env))
         (eval-seq (cdar clauses) env))
        (else (eval-cond (cdr clauses) env))))

(define (make-proc params body env) (list 'proc params body env))
(define (proc? x) (and (pair? x) (eq? (car x) 'proc)))

(define (m-apply f args)
  (if (proc? f)
      (eval-seq (caddr f)
                (extend-env (cadr f) args (cadddr f)))
      (apply f args)))

;;; 環境:框架的串列,每個框架是可變的 (名稱 . 值) 關聯串列
(define (extend-env names vals env)
  (cons (map cons names vals) env))
(define (find-binding name env)
  (if (null? env)
      #f
      (or (assq name (car env)) (find-binding name (cdr env)))))
(define (lookup name env)
  (let ((b (find-binding name env)))
    (if b (cdr b) (error "metacircular: unbound variable" name))))
(define (set-var! name val env)
  (let ((b (find-binding name env)))
    (if b (set-cdr! b val) (error "metacircular: unbound variable" name))))
(define (define-var! name val env)
  (let ((b (assq name (car env))))
    (if b
        (set-cdr! b val)
        (set-car! env (cons (cons name val) (car env))))
    name))

(define global-env
  (list (list (cons '+ +) (cons '- -) (cons '* *) (cons '< <) (cons '= =)
              (cons 'car car) (cons 'cdr cdr) (cons 'cons cons)
              (cons 'null? null?) (cons 'list list) (cons 'display display))))

(define (run exp)
  (let ((v (m-eval exp global-env)))
    (write exp) (display "  =>  ") (write v) (newline)))

(run '(+ 1 2))
(run '(define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))))
(run '(fact 10))
(run '(define (map1 f l) (if (null? l) (quote ()) (cons (f (car l)) (map1 f (cdr l))))))
(run '(map1 (lambda (x) (* x x)) (list 1 2 3 4 5)))
(run '(let ((x 3) (y 4)) (+ (* x x) (* y y))))
(run '(define counter 0))
(run '(begin (set! counter (+ counter 1)) (set! counter (+ counter 1)) counter))
(run '(define (fib n) (cond ((< n 2) n) (else (+ (fib (- n 1)) (fib (- n 2)))))))
(run '(fib 15))
